//BoardRedux --> BoardRedux
export const HANDLE_PIECE_CLICK = "HANDLE_PIECE_CLICK";
export const CLEAR_SELECTION = "CLEAR_SELECTION";
//API_StateChGaming --> GameData
export const MERGE_BLOCKCHAIN_GETGAME = "MERGE_BLOCKCHAIN_GETGAME";
//API_Database --> GameData
export const MERGE_DATABASE_GETGAME = "MERGE_DATABASE_GETGAME";
//GameData --> GameData
export const RESET_GAME_DATA = "RESET_GAME_DATA";
//API_ERC20 --> TempUserInputs
export const UPDATE_APPROVALS = "UPDATE_APPROVALS";
//LOGIN --> Login details
export const CHANGE_ADDRESS_TEXT = "CHANGE_ADDRESS_TEXT";
export const HANDLE_PRIVKEY_CHANGE = "HANDLE_PRIVKEY_CHANGE";
//direct to TempUserInputs
export const SET_MOVETYPE_DB = "SET_MOVETYPE_DB";
export const SET_MOVETYPE_BCENFORCED = "SET_MOVETYPE_BCENFORCED";
export const SET_MOVETYPE_BCUNENFORCED = "SET_MOVETYPE_BCUNENFORCED";
