//GAME BOARD RELATED
export const HANDLE_PIECE_CLICK = "HANDLE_PIECE_CLICK";
export const SET_BOARD_MATRIX = "SET_BOARD_MATRIX";
export const HANDLE_MOVE = "HANDLE_MOVE";
export const CLEAR_SELECTION = "CLEAR_SELECTION";
export const PREV_MOVE_STATS = "PREV_MOVE_STATS";

//GAME DATA RELATED
export const MERGE_BLOCKCHAIN_GETGAME = "MERGE_BLOCKCHAIN_GETGAME";
export const MERGE_DATABASE_GETGAME = "MERGE_DATABASE_GETGAME";
export const RESET_GAME_DATA = "RESET_GAME_DATA";

//BLOCKCHAIN RELATED
export const UPDATE_APPROVALS = "UPDATE_APPROVALS";

//LOGIN DETAILS RELATED
export const CHANGE_ADDRESS_TEXT = "CHANGE_ADDRESS_TEXT";
export const HANDLE_PRIVKEY_CHANGE = "HANDLE_PRIVKEY_CHANGE";

