export const HANDLE_PIECE_CLICK = "HANDLE_PIECE_CLICK";
// export const SET_ACTIVE_CHANNEL = "SET_ACTIVE_CHANNEL";
// export const HANDLE_PRIVKEY_CHANGE = "HANDLE_PRIVKEY_CHANGE";
// export const HANDLE_SHOW_NEW_CHANNEL_FORM_TOGGLE = "HANDLE_SHOW_NEW_CHANNEL_FORM_TOGGLE";