// export const CHANGE_GAMEID_TEXT = "CHANGE_GAMEID_TEXT";
export const MERGE_BLOCKCHAIN_GETGAME = "MERGE_BLOCKCHAIN_GETGAME";
export const MERGE_DATABASE_GETGAME = "MERGE_DATABASE_GETGAME";
export const RESET_GAME_DATA = "RESET_GAME_DATA";

